### ISSUE TITLE
Unable to able porto file into webots simulation

### ISSUE THREAD

**Issue by SunnyKatyara** [cyberbotics/urdf2webots#25]
Hello,

I have converted my urdf into porto file but unable to import it.

1. In my project, my porto file is available in portos
2. Launching simulation with emoty.wbt
2. When i add with porto nodes, i am unable to see the file.

I do not what is missing ?

**Comment by DavidMansolino** [comment]
If you did correctly add the `panda.proto` file to the `protos` folder you should be able to add it to the simulation like this:
![Capture du 2019-09-20 17-58-57](https://user-images.githubusercontent.com/2461619/65341297-565b1100-dbd0-11e9-8971-80a746e06f73.png)
If it is not working try to close and re-open Webots (it my require to restart to update the list of protos).

**Comment by SunnyKatyara** [comment]
![Screenshot from 2019-09-20 18-09-57](https://user-images.githubusercontent.com/52322093/65341997-1137de80-dbd2-11e9-9622-27b14e36b887.png)
It is giving me this error

**Comment by SunnyKatyara** [comment]
If possible can you please share with me that proto file that you created. I am new to webots and i really want to explore it for my research.

**Comment by SunnyKatyara** [comment]
I tried but it is showing me errors all the time. Attached is the conversion data. 
1. It is saying can not determine package root path
2. Unsupported "R8G8B8" image format, using "R8G8B8A8" instead.


![Screenshot from 2019-09-21 11-23-44](https://user-images.githubusercontent.com/52322093/65371264-599edd00-dc62-11e9-9f65-ac6ca84623cf.png)
![Screenshot from 2019-09-21 11-23-50](https://user-images.githubusercontent.com/52322093/65371267-5c013700-dc62-11e9-94ee-be2f4c9465e8.png)

**Comment by SunnyKatyara** [comment]
Hello, i can import other protos from webots library but the one that i create is showing me these errors. Can you please help me to figure it out.

Thank you

**Comment by DavidMansolino** [comment]
> It is giving me this error

You can ignore these errors in a first step, they will not prevent you from using the proto.

> If possible can you please share with me that proto file that you created. I am new to webots and i really want to explore it for my research.

Here is the file: 
[Panda.proto.zip](https://github.com/cyberbotics/urdf2webots/files/3642107/Panda.proto.zip)

> It is saying can not determine package root path

This means that you did miss some file path update when you edited the URDF file. You should not have any more `package://tutorial_iros2018/...` in your URDF file:
You should do a search and replace for the `package://tutorial_iros2018/robots/` string and replace it by the actual path to your `panda` folder.

> Unsupported "R8G8B8" image format, using "R8G8B8A8" instead.

This message just say that the camera will use the `R8G8B8A8` image format instead of the `R8G8B8` one.

Let me know if you still have issues.

**Comment by SunnyKatyara** [comment]
Thanks! Its working

**Comment by DavidMansolino** [comment]
You're welcome :wink:
